matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx

env:
  global:
    - TWINE_USERNAME=joerick
      # Note: TWINE_PASSWORD is set in Travis settings

script:
  - pip install https://github.com/hroncok/cibuildwheel/archive/patch-1.zip
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m pip install twine
      python -m twine upload wheelhouse/*.whl
    fi
